trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: self
    type: git
    name: Santhosh-m2004/maventestazure
    endpoint: new connection   # Your PAT service connection name

steps:
- checkout: self
  persistCredentials: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
