trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # ✅ Correct path based on your structure
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
